### ISSUE TITLE
401 Response

### ISSUE THREAD

**Issue by ademenev** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#2]
```bash
bash-3.2$ node app.js
Running Drop
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (401)
    at ClientRequest._req.on (/private/tmp/azure-cosmos-db-graph-nodejs-getting-started/node_modules/ws/lib/WebSocket.js:650:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
bash-3.2$
```

I have double checked all settings in config.js

**Comment by sidharthchugh** [comment]
i am also getting same error

**Comment by Walls** [comment]
Same error for me. all Primary key and Url are correct.

**Comment by jagratimodi** [comment]
It gives error if you give endpoint as **account_name.graphs.azure.com:443/**. Error gets resolved by giving endpoint as only **account_name.graphs.azure.com**.

**Comment by hannupekka** [comment]
Getting same error. Endpoint is in format `account_name.documents.azure.com` - copied from Azure dashboard.

Trying to access endpoint with Postman gives this response: `Authorization header doesn't confirm to the required format. Please verify and try again.`

I've copied primary key from the same dashboard.

**Comment by hannupekka** [comment]
Alright got it working. Needed to use `account_name.graphs.azure.com` instead of `account_name.documents.azure.com`

**Comment by craiha** [comment]
It seems like you also need to wait for some time even though everything is correct. For me it started to work 1h after I created the database.

**Comment by LuisBosquez** [comment]
This error should now be fixed. The explanation is that you need to use the graph endpoint with the following format: `luis_endpoint.gremlin.cosmosdb.azure.com`

Please refer to the latest version of the sample, and the `config.js` file, for clarification.
