### ISSUE TITLE
Unexpected Server Response

### ISSUE THREAD

**Issue by xocolatl-aficionado** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#22]
```
C:\Users\<>\Desktop\graphAPI\azure-cosmos-db-graph-nodejs-getting-started>node app.js
Running Drop
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (200)
    at ClientRequest._req.on (C:\Users\<>\Desktop\graphAPI\azure-cosmos-db-graph-nodejs-getting-started\node_modules\ws\lib\WebSocket.js:650:26)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

![image](https://user-images.githubusercontent.com/17209734/43472295-bb9493e0-94b2-11e8-9650-f2818125642c.png)

Is this a deprecation problem? How can I fix it?

**Comment by xocolatl-aficionado** [comment]
Nvm. Rookie error. Was trying to use this tutorial with a mongo API Cosmos resource. Works now. However I'd love to know what that DEPRECATED tag in the docs mean. 
Should we be shifting away from gremlin?

**Comment by LuisBosquez** [comment]
@xocolatl-aficionado, the DEPRECATED means that the main development for the Gremlin-Javascript driver is happening in the official Tinkerpop repository: https://github.com/apache/tinkerpop/tree/master/gremlin-javascript 

I'm assuming this README is from this repository: https://github.com/jbmusso/gremlin-javascript
